[phases.setup]
nixPkgs = ["nodejs_23"]

[phases.install]
cmds = [
  "npm install -g corepack@latest && corepack enable",
  "NODE_OPTIONS=--experimental-sqlite pnpm i --frozen-lockfile"
]

[phases.build]
cmds = [
  "find node_modules/.pnpm -name 'esbuild' -path '*/bin/esbuild' -exec chmod +x {} \\; && NODE_OPTIONS=--experimental-sqlite pnpm --filter=web run build"
]

[start]
cmd = "node apps/web/dist/server/entry.mjs"
