[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install -g corepack@latest && corepack enable",
  "pnpm i --frozen-lockfile"
]

[phases.build]
cacheDirectories = ["apps/web/.astro", "node_modules/.cache"]
cmds = [
  "pnpm run build:vps"
]

[start]
cmd = "node apps/web/dist/server/entry.mjs"
