[phases.setup]
nixPkgs = ["nodejs_24"]

[phases.install]
cmds = [
  "npm install -g corepack@latest && corepack enable",
  "pnpm i --frozen-lockfile"
]

[phases.build]
cacheDirectories = ["apps/web/.astro", "node_modules/.cache"]
cmds = [
  "corepack enable && DEPLOY_TARGET=vps pnpm --filter @madavi/web run build:ci"
]

[start]
cmd = "node apps/web/dist/server/entry.mjs"
